plugins_preset: "all" # Valid values are "default", "all" or "none".
plugins:
  dbinfo:
    disabled: false
    pkgname: "dbinfo"
    destination: "pkg/gen/dbinfo"
  enums:
    disabled: false
    pkgname: "enums"
    destination: "pkg/gen/enums"
  models:
    disabled: false
    pkgname: "models"
    destination: "pkg/gen/models"
  factory:
    disabled: false
    pkgname: "factory"
    destination: "pkg/gen/factory"
  dberrors:
    disabled: false
    pkgname: "dberrors"
    destination: "pkg/gen/dberrors"
  where:
    disabled: false
  loaders:
    disabled: false
  joins:
    disabled: false
mysql:
  # データベースのDSN
  dsn: root:p@ssw0rd@tcp(localhost:13306)/sample
